version: "3.9"

services:
  notes-api:
    image: python:3.12-slim          # fertiges Image von Docker Hub
    container_name: notes-api
    working_dir: /app                # Arbeitsverzeichnis im Container
    volumes:
      - .:/app                       # aktueller Ordner wird in /app gemountet
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python app.py"
    restart: unless-stopped