apiVersion: v1
kind: Service
metadata:
  name: notes-api-service
spec:
  selector:
    app: notes-api
  type: ClusterIP          # Intern erreichbar
  ports:
    - protocol: TCP
      port: 5000          # Service-Port
      targetPort: 5000    # Container-Port